#!/bin/bash

# Run GATK4 GetPileupSummaries
# 1 task = 1 bam
# 28Gb mem per task, ~ 25min walltime

#PBS -P hm82
#PBS -N getpileupsummaries
#PBS -l walltime=15:00:00,ncpus=48,mem=1500GB,wd
#PBS -q hugemem
#PBS -W umask=022
#PBS -l storage=scratch/er01+scratch/hm82+scratch/oj47+scratch/public
#PBS -o ./Logs/gatk4_getpileupsummaries/getpileupsummaries_missing.o
#PBS -e ./Logs/gatk4_getpileupsummaries/getpileupsummaries_missing.e

set -e

module load openmpi/4.0.2
module load nci-parallel/1.0.0

# SCRIPT
SCRIPT=./gatk4_getpileupsummaries.sh
INPUTS=./Inputs/gatk4_getpileupsummaries_missing.inputs

# M = Number of tasks per node
# NCPUs = CPUs per task
M=24
NCPUS=2

echo "$(date): GATK 4 GetPileupSummaries for tumour normal pairs"

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / CPN)) \
	--map-by node:PE=${NCPUS} \
	nci-parallel \
	--verbose \
	--input-file ${PBS_JOBFS}/input-file

