#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Usage: qsub gatk4_getpileupsummaries_split_common_vcf.pbs
# Version: 1.0
#
# For more details see: https://github.com/Sydney-Informatics-Hub/Somatic-ShortV
#
# If you use this script towards a publication, support us by citing:
#
# Suggest citation:
# Sydney Informatics Hub, Core Research Facilities, University of Sydney,
# 2021, The Sydney Informatics Hub Bioinformatics Repository, <date accessed>,
# https://github.com/Sydney-Informatics-Hub/Germline-ShortV
#
# Please acknowledge the Sydney Informatics Hub and the facilities:
#
# Suggested acknowledgement:
# The authors acknowledge the technical assistance provided by the Sydney
# Informatics Hub, a Core Research Facility of the University of Sydney
# and the Australian BioCommons which is enabled by NCRIS via Bioplatforms
# Australia. The authors acknowledge the use of the National Computational
# Infrastructure (NCI) supported by the Australian Government.
#
#########################################################

#PBS -P xh27
#PBS -N split-vcf
#PBS -l walltime=00:30:00
#PBS -l ncpus=1
#PBS -l mem=9GB
#PBS -l wd
#PBS -q normalbw
#PBS -W umask=022
#PBS -l storage=scratch/er01+gdata/er01


set -e

module load gatk/4.2.1.0

gatk SelectVariants \
	--java-options "-Xmx8g -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" \
	-R $ref \
	-V $common_biallelic \
	-L $interval \
	-O $out > $log 2>&1
