#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Description: Runs gatk4_filtermutectcalls.sh in parallel, which
# filters tumour_normal unfiltered VCFs using gatk4_filtermutectcalls_run_parallel.pbs
# Usage: Adjust <project> and compute resource requests following the guide
# Job resource requirements:
# Per task requirements:
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
# Date last modified: 24/02/2021
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested citation:
# Sydney Informatics Hub, Core Research Facilities, University of Sydney,
# 2021, The Sydney Informatics Hub Bioinformatics Repository, <date accessed>,
# https://github.com/Sydney-Informatics-Hub/Bioinformatics
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P <project>
#PBS -N filtermutectcalls
#PBS -l walltime=02:00:00,ncpus=48,mem=190GB,wd
#PBS -q normal
#PBS -W umask=022
#PBS -l storage=scratch/<project>
#PBS -o ./Logs/filtermutectcalls.o
#PBS -e ./Logs/filtermutectcalls.e

set -e

INPUTS=./Inputs/gatk4_filtermutectcalls.inputs

#########################################################
# Do not edit below this line
#########################################################

module load openmpi/4.1.0
module load nci-parallel/1.0.0a
module load gatk/4.1.2.0

# NCPUs = CPUs per task
NCPUS=1

# SCRIPT
SCRIPT=./gatk4_filtermutectcalls.sh

if [[ $PBS_QUEUE =~ bw-exec ]]; then CPN=28; else CPN=48; fi
M=$(( CPN / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / CPN)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file
