#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Description: Runs gatk4_pon.sh in parallel, which calls variants
# using Mutect2 in tumour only mode from normal sample BAMs with inputs
# created by gatk4_pon_make_input.sh
# Usage: Adjust <project> and compute resource requests following the guide
# below, then qsub gatk4_pon_run_parallel.pbs
# Job resource requirements:
# walltime=02:00:00 (job expected to complete in ~1 hour for 30-60X)
# ncpus=48*2*N (N=number of samples in ../<cohort>.config)
# mem=192*2*N GB (N=number of samples in ../<cohort>.config)
# Per task requirements:
# 1 task requires 1 CPU, 4GB mem
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
# Date last modified: 18/03/2021
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P <project>
#PBS -N gatk4_pon
#PBS -l walltime=02:00:00,ncpus=1152,mem=4608GB,wd
#PBS -q normal
#PBS -W umask=022
#PBS -l storage=scratch/<project>
#PBS -o ../Logs/pon.o
#PBS -e ../Logs/pon.e

INPUTS=./Inputs/gatk4_pon.inputs

#########################################################
# Do not edit below this line
#########################################################

module load openmpi/4.0.2
module load nci-parallel/1.0.0
module load gatk/4.1.2.0

set -e

# NCPUs = CPUs per task
NCPUS=1

# SCRIPT
SCRIPT=./gatk4_pon.sh

if [[ $PBS_QUEUE =~ bw-exec ]]; then CPN=28; else CPN=48; fi
M=$(( CPN / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / CPN)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file
