#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Usage: qsub gatk4_cohort_pon_gather_sort.pbs
# Version: 1.0
#
# For more details see: https://github.com/Sydney-Informatics-Hub/Somatic-ShortV
#
# If you use this script towards a publication, support us by citing:
#
# Suggest citation:
# Sydney Informatics Hub, Core Research Facilities, University of Sydney,
# 2021, The Sydney Informatics Hub Bioinformatics Repository, <date accessed>,
# https://github.com/Sydney-Informatics-Hub/Germline-ShortV
#
# Please acknowledge the Sydney Informatics Hub and the facilities:
#
# Suggested acknowledgement:
# The authors acknowledge the technical assistance provided by the Sydney
# Informatics Hub, a Core Research Facility of the University of Sydney
# and the Australian BioCommons which is enabled by NCRIS via Bioplatforms
# Australia. The authors acknowledge the use of the National Computational
# Infrastructure (NCI) supported by the Australian Government.
#
#########################################################


#PBS -P er01
#PBS -N cohort_pon_gather_sort
#PBS -l walltime=00:15:00,ncpus=1,mem=10GB,wd
#PBS -q express
#PBS -W umask=022
#PBS -l storage=XXX
#PBS -o ./Logs/gatk4_cohort_pon_gather_sort.o
#PBS -e ./Logs/gatk4_cohort_pon_gather_sort.e

set -e

module load gatk/4.2.1.0

# CHANGE THIS
config=../samplesSet1-3.config

# Do not change below
cohort=$(basename "$config" | cut -d. -f 1)
INPUTS=./Inputs
scatterdir=../Reference/ShortV_intervals
scatterlist=$(ls $scatterdir/*.list)
if [[ ${#scatterlist[@]} > 1 ]]; then
        echo "$(date): ERROR - more than one scatter list file found: ${scatterlist[@]}"
        exit
fi
vcfdir=../$cohort\_cohort_PoN
logdir=./Logs/gatk4_cohort_pon_gather_sort
args=${INPUTS}/gatk4_cohort_pon_gather_sort.inputs
unsorted=${vcfdir}/${cohort}.pon.vcf.gz
sorted=${vcfdir}/${cohort}.sorted.pon.vcf.gz
num_int=`wc -l ${scatterlist} | cut -d' ' -f 1`

rm -rf ${args}

for interval in $(seq -f "%04g" 0 $((${num_int}-1)));do
        echo "-I" ${vcfdir}/${cohort}.${interval}.pon.vcf.gz >> ${args}
done

mkdir -p ${logdir}

# Gather per interval cohort vcf.gz files into a single .vcf.gz file
# Less KSU to create MD5 later
gatk GatherVcfs \
        --arguments_file ${args} \
        --MAX_RECORDS_IN_RAM 100000000 \
        -O ${unsorted} > ${logdir}/${cohort}_gathervcfs.log 2>&1


# Sort vcf.gz file - in case GatherVcfs fails to make index file (will happen if you output gzipped file)
# Ensures vcf.gz is sorted
gatk SortVcf \
        -I ${unsorted} \
        -O ${sorted} > ${logdir}/${cohort}_sortvcf.log 2>&1
