#! /bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Description: Select common biallelic variants from a public resource
# Common biallelic variants are used in GetPileupSummaries and CalculateContamination
# Usage: Adjust variables refdir=, resource=,a nd resource_common=
# The resource variable is your public variants in VCF format
# The common biallelic variants selected from the public resource is
# saved in the output file of the resource_common= variable
# Adjust <project> and compute resource requests following the guide
# below, then qsub gatk4_selectvariants.pbs
# Job resource requirements:
# walltime=02:00:00 (job expected to complete in ~1 hour for 30-60X)
# ncpus=48*2*N (N=number of samples in ../<cohort>.config)
# mem=192*2*N GB (N=number of samples in ../<cohort>.config)
# Per task requirements:
# 1 task requires 1 CPU, 4GB mem
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
# Date last modified: 18/03/2021
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P <project>
#PBS -N selectvariants
#PBS -l walltime=04:00:00,ncpus=48,mem=192GB,wd
#PBS -q normal
#PBS -W umask=022
#PBS -l storage=scratch/<project>
#PBS -o ./Logs/selectvariants.o
#PBS -e ./Logs/selectvariants.e

logdir=./Logs/gatk4_selectvariants
refdir=../Reference/gatk-best-practices/somatic-hg38
resource=${refdir}/af-only-gnomad.hg38.vcf.gz
resource_common=${refdir}/af-only-gnomad.common_biallelic.hg38.vcf.gz

set -e

module load gatk/4.1.2.0

mkdir -p ${logdir}

gatk --java-options "-Xmx192g" SelectVariants \
        -V ${resource} \
        -select-type SNP -restrict-alleles-to BIALLELIC \
        -select "AF > 0.05" \
        -O ${resource_common} \
        --lenient
