#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Description: Runs gatk4_learnreadorientationmodel.sh in parallel
# Usage: Adjust <project> and compute resource requests following the guide
# below, then qsub gatk4_learnreadorientationmodel_run_parallel.pbs
# Job resource requirements:
#       1 hugemem node to run 24 samples in parallel
#       For 26 samples, usage was for 1 hugemem node was:
#       1.42TB memory used, walltime=02:27:59, SU=355.16, E=0.37
# Per task requirements:
#       1 task (1 tumour-normal pair): 1CPU 28GB mem on average
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
# Date last modified: 24/02/2021
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested citation:
# Sydney Informatics Hub, Core Research Facilities, University of Sydney,
# 2021, The Sydney Informatics Hub Bioinformatics Repository, <date accessed>,
# https://github.com/Sydney-Informatics-Hub/Bioinformatics
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P <project>
#PBS -N learnreadorientation
#PBS -l walltime=05:00:00,ncpus=48,mem=1500GB,wd
#PBS -q hugemem
#PBS -W umask=022
#PBS -l storage=scratch/<project>
#PBS -o ../Logs/learnreadorientation.o
#PBS -e ../Logs/learnreadorientation.e

set -e

INPUTS=./Inputs/gatk4_learnreadorientationmodel.inputs

#########################################################
# Do not edit below this line
#########################################################

module load openmpi/4.1.0
module load nci-parallel/1.0.0a
module load gatk/4.1.2.0

# NCPUs = CPUs per task
NCPUS=2

# SCRIPT
SCRIPT=./gatk4_learnreadorientationmodel.sh

if [[ $PBS_QUEUE =~ bw-exec ]]; then CPN=28; else CPN=48; fi
M=$(( CPN / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / CPN)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file
