#!/bin/bash

# Run GATK4 MergeMutectStats to merge per interval stats files per tumour-normal pair
# 1 task = 1 TN pair

#PBS -P hm82
#PBS -N mergemutectstats
#PBS -l walltime=00:30:00,ncpus=48,mem=192GB,wd
#PBS -q normal
#PBS -W umask=022
#PBS -l storage=scratch/er01+scratch/hm82+scratch/oj47+scratch/public
#PBS -o ./Logs/gatk4_mergemutectstats/mergemutectstats.o
#PBS -e ./Logs/gatk4_mergemutectstats/mergemutectstats.e

set -e

module load openmpi/4.0.2
module load nci-parallel/1.0.0

# SCRIPT
SCRIPT=./gatk4_mergemutectstats.sh
INPUTS=./Inputs/gatk4_mergemutectstats.inputs

# M = Number of tasks per node
# NCPUs = CPUs per task
M=48
NCPUS=1

echo "$(date) : GATK 4 MergeMutectStats for tumour normal pairs"

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / CPN)) \
	--map-by node:PE=${NCPUS} \
	nci-parallel \
	--verbose \
	--input-file ${PBS_JOBFS}/input-file
